### ISSUE TITLE
Wrong tagify tag value on press right button on keyboard (autocomplete enabled)

### ISSUE THREAD

**Issue by 7iomka** [yairEO/tagify#358]
### Demo 
https://youtu.be/45suBs2yrSM

### Explanation

This bug occurs when you use custom dropdownItem template.
When you select item from dropdown with mouse or with navigation button (up/down) and press enter - all works as expected. 
But, if you use navigation buttons to select needed item, and after that press right arrow button (that is the most commonly used behavior), you will see unexpected result in tag value!

**Comment by yairEO** [comment]
I have re-written a lot of parts of Tagify for the upcoming version `v3` which will be released in 2 days hopefully so lets see if this still happens then.

For now, it would be quite helpful if you posted your custom template as well.

**Comment by 7iomka** [comment]
> I have re-written a lot of parts of Tagify for the upcoming version `v3` which will be released in 2 days hopefully so lets see if this still happens then.
> 
> For now, it would be quite helpful if you posted your custom template as well.

I don't know good react, maybe you will help be, but I posted my settings:
https://codesandbox.io/embed/tagify-react-wrapper-hfn9i?fontsize=14&hidenavigation=1&theme=dark
I used default demo for react
CrazyTags.js
line 13 - I get prepared html template using Handlebars (template available in DOM in file public/index.html)
line 17 - this is my tagifySettings

line 53 - this is my callback that i needed to apply on input like this
input.on('input', onInputTagify(input));
but I don't know react, and I don’t know where I should use this function (maybe you can help me)
Well, or later, maybe I can deploy an example not on the codepen framework.
Thanks.

**Comment by 7iomka** [comment]
> I have re-written a lot of parts of Tagify for the upcoming version `v3` which will be released in 2 days hopefully so lets see if this still happens then.
> 
> For now, it would be quite helpful if you posted your custom template as well.
Ok - see please
https://codepen.io/7iomka/pen/vYENwrO?editors=1010

**Comment by yairEO** [comment]
Just released version `3.0.0` so this should work. Try updating Tagify and check. this should be fixed. Try and let me know.

**Comment by 7iomka** [comment]
> Just released version `3.0.0` so this should work. Try updating Tagify and check. this should be fixed. Try and let me know.

I updated to latest version, and problem still remaining :-(
Video demo: https://www.youtube.com/watch?v=GpY1TGlm-DE
Same link for codepen demo: https://codepen.io/7iomka/pen/vYENwrO?editors=1010

**Comment by yairEO** [comment]
I am investigating.

**Comment by yairEO** [comment]
Ok, pushed a fix (`v 3.1.0`). I've made a [demo for you](https://jsbin.com/rizorocezu/1/edit?html,js,output)

Here is the Tagify settings I've used:

```
{
  autoComplete : {
    rightKey:true
  },
  dropdown: {
    enabled: 1,
    mapValueTo: "email"
  },
  whitelist:[
    {
      value: 'Chris Muller',
      email: 'chris.muller@gmail.com',
    },
    {
      value: 'Alon Silko',
      email: 'alon@gmail.com',
    },
  ]
}
```
