### ISSUE TITLE
Cursor does not display in the correct position on FireFox when focusing the Tagify input

### ISSUE THREAD

**Issue by braydensterrett** [yairEO/tagify#533]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

Not including a demo, because this issue can be seen on the demo page provided by tagify at:

https://yaireo.github.io/tagify/

### Explanation

- **What is the expected behavior?**

The cursor in the latest version of FireFox browser should appear centered vertically and within the tagify textbox when focusing the textbox. 

- **What is happening instead?**

The cursor in the latest version of FireFox browser does not display correctly when focusing the tagify textbox and is tiny and offset to the top of the box. 

Example on the Tagify demo page:
![tagify_evidence](https://user-images.githubusercontent.com/7805772/83538784-dce42400-a4bb-11ea-9123-cd0e614bf7d5.gif)

I saw an old post about something similar to this and it was recommended to make sure that you're using the latest version of the CSS. I've confirmed that I am using the latest version of the CSS and still seeing this issue. 

- **What error message are you getting?**

No errors.

**Comment by kerolloz** [comment]
facing the same issue

**Comment by kerolloz** [comment]
I think the issue is fixed now @braydensterrett

**Comment by yairEO** [comment]
No it still happens. It's a very old bug in Firefox mozilla doesn't care to fix.

I've discussed this on [Stackoverflow 6 years ago](https://stackoverflow.com/q/21986985/104380)

you can help by starring the issue on mozilla (link inside the stackoverflow discussion)

**Comment by braydensterrett** [comment]
It does appear that this has been fixed in both my application, and on the tagify example page. Whatever happened, it's working as intended. Appreciate your time on this.
