### ISSUE TITLE
In Mix mode, tags are unintentionally deleted while using the Delete or Backspace keys

### ISSUE THREAD

**Issue by sbvltr** [yairEO/tagify#678]
I've tested with the latest release, and reproduced on the demo page.

While typing regular text, if you press the delete button at the end of the string, it will remove tags from last to first.   Pressing backspace is harder to reproduce.  I was able to reproduce by typing space then backspace continuously at the end of a text string (away from the tag).

This obviously makes tagging difficult as a tag will be unintentionally deleted while editing another area of text.

**Comment by chamboug** [comment]
I was about to open a similar issue as well. When I press delete in the text or before a tag it works well, but something is wrong when pressing delete at the end of the input.

![bLZE09gvLh](https://user-images.githubusercontent.com/11667428/96427513-ee299500-11fe-11eb-8361-a9a01a90197a.gif)

**Comment by yairEO** [comment]
fixed on `tagify@3.20.1`

**Comment by sbvltr** [comment]
I just tested this in my own app and in your demo and the issue still exists.   Tested with Chrome 86 on windows.
